name: 🐛 Bug Report
description: File a bug report to help us improve
title: "[BUG] <describe the bug>"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please complete the following form to help us address it faster.

  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, runtime, libraries, versions, etc.
      placeholder: e.g. Ubuntu 22.04, Python 3.11, Node.js 18.x
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
      placeholder: The system crashes when I...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How do we reproduce the bug?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen instead?
      placeholder: I expected it to return a 200 OK...

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs or Screenshots
      description: Paste any error logs or attach screenshots.
      placeholder: |
        ```
        Error: Cannot read property 'x' of undefined
        at index.js:32:5
        ```

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this issue?
      options:
        - 🔴 Critical (blocks release)
        - 🟠 High
        - 🟡 Medium
        - 🟢 Low
