name: ✨ Feature Request
description: Suggest a new idea or improvement
title: "[FEATURE] <your idea here>"
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below.

  - type: input
    id: motivation
    attributes:
      label: What problem are you trying to solve?
      description: Describe the user need or pain point.
      placeholder: I want to automate...
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Describe the Solution
      description: What would you like to see added?
      placeholder: I suggest we implement...

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternatives?
      placeholder: I also considered...

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      options:
        - 🚀 High (strategic / important for many users)
        - ✅ Medium (valuable enhancement)
        - 💡 Low (nice-to-have)
