name: Scheduled API Call

on:
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call API and Save Response
        run: |
          echo "Calling API..."

          RESPONSE=$(curl -s -X POST https://your-api.com/endpoint \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.OLLAMA_HOST }}" \
            -d '{"model":"gemma3n:e4b","prompt":"What is the capital of France?","stream":false}'
          )

          echo "Response received:"
          echo "$RESPONSE"

          echo "$RESPONSE" > api_response_$(date +%Y%m%d_%H%M%S).json
    
      - name: Upload API Response as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-response
          path: api_response_*.json
